Repository nbc-react-3rd-outsourcing-project-a5/outsourcing-project, pull requests merged in 2023-12, with the labels that each got.

#10 [feature/carousel] 캐러셀 구현 #7
  package-lock.json
  package.json
  src/components/Carousel/Carousel.jsx
  src/pages/Home/index.jsx
Labels: 🎉 add, 💄 style

#12 test
  src/data/testData.txt
Labels: 🍻 test

#13 [feature/layout] : Header, Footer 추가 (#9)
  public/index.html
  src/components/Footer.jsx
  src/components/Header.jsx
  src/fonts.css
  src/shared/Layout.jsx
  src/styles/GlobalStyle.jsx
Labels: ✨ update, 🎉 add, 💄 style

#15 [feature/homeContents] 홈화면 진행 중과 진행 예정인 축제 UI 구현 (#11)
  src/components/Carousel/Carousel.jsx
  src/components/HomeContents/HomeContents.jsx
  src/pages/Home/index.jsx
Labels: 🎉 add, 💄 style

#18 Feature/popular carousel 인기 축제 카르셀 추가
  package.json
  src/components/Popular/Popular.jsx
  src/components/Popular/popularData.json
  src/components/Search/SearchForm.jsx
  src/pages/Home/index.jsx
Labels: 🎉 add

#21 [feature/festivalRegistrationForm] 축제 등록 폼 UI 구성 #19
  package-lock.json
  package.json
  src/components/FestivalRegistration/FestivalRegistrationForm.jsx
  src/pages/FestivalRegistration/FestivalRegistration.jsx
  src/shared/Router.jsx
Labels: ✨ update, 🎉 add, 🩹 fix, 💄 style

#23 [feature/layout] : 공통 스타일드 컴포넌트 생성, 헤더 상단에 고정
  public/index.html
  src/components/Carousel/Carousel.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/HomeContents/HomeContents.jsx
  src/components/Popular/Popular.jsx
  src/components/common/StButton.js
  src/components/common/StContainer.js
  src/components/common/StInput.js
  src/components/common/StVwContainer.js
  src/styles/GlobalStyle.jsx
Labels: 🎉 add, 💄 style

#25 [feature/Firebase] 파이어베이스 연결 #14
  package-lock.json
  package.json
  src/components/FestivalRegistration/FestivalRegistrationForm.jsx
  src/fb/firebase.js
  src/hooks/index.js
  src/hooks/useDate.js
  src/hooks/useFestival.js
  src/hooks/useImageFile.js
  src/hooks/useInput.js
  src/index.js
  src/redux/config/configStore.js
  src/redux/modules/festivalSlice.js
  src/redux/modules/testSlice.js
  src/utils/fireStorage.js
Labels: ✨ update, 🎉 add, ♻️ refactor, 🩹 fix

#27 update: router 정리 (#26)
  src/components/Header.jsx
  src/pages/Auth/Auth.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Search/Search.jsx
  src/pages/User/User.jsx
  src/shared/Router.jsx
Labels: ✨ update, 🩹 fix

#28 [feature/firebaseLogin] 로그인 기능 구현 #24
  src/App.jsx
  src/components/Auth/AuthIndex.jsx
  src/components/Auth/GenernalLogin.jsx
  src/components/Auth/Login.jsx
  src/components/Auth/OrganizerLogin.jsx
  src/components/Header.jsx
  src/fb/firebase.js
  src/pages/Auth/Auth.jsx
  src/redux/config/configStore.js
  src/redux/modules/authSlice.js
  src/shared/Router.jsx
Labels: ✨ update, 🎉 add, 🩹 fix, 💄 style

#29 [feature/detail] detail 페이지 등 수정
  src/components/Carousel/Carousel.jsx
  src/components/FestivalRegistration/FestivalRegistrationForm.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/HomeContents/HomeContents.jsx
  src/components/Popular/Popular.jsx
  src/components/common/StVwContainer.js
  src/hooks/useFestival.js
  src/pages/Detail/Detail.jsx
  src/redux/modules/festivalSlice.js
  src/shared/Router.jsx
Labels: 🎉 add, 🩹 fix, 💄 style

#30 Feature/search form 검색 필터링 기능 추가 및 UI 구현
  src/components/Popular/Popular.jsx
  src/components/Search/SearchForm.jsx
  src/components/SearchForm/FormSelect.jsx
  src/components/SearchForm/SearchForm.jsx
  src/components/SearchForm/TestImg.jsx
  src/components/SearchForm/assets/resetIcon.png
  src/data/regionList.json
  src/data/testData.txt
  src/pages/Search/Search.jsx
Labels: ✨ update

#34 [feature/comments] 댓글 CRUD 구현 #33
  src/App.jsx
  src/components/Comments/Comments.jsx
  src/components/Header.jsx
  src/pages/Detail/Detail.jsx
  src/redux/modules/authSlice.js
Labels: ✨ update, 🎉 add, 💄 style

#32 [feature/reactToastify] react-toastify라이브러리 적용 #31
  package-lock.json
  package.json
  src/App.jsx
  src/components/Auth/GenernalLogin.jsx
  src/components/Auth/Login.jsx
  src/components/Auth/OrganizerLogin.jsx
  src/components/Comments/Comments.jsx
  src/components/Header.jsx
  src/hooks/useImageFile.js
Labels: ✨ update, 🩹 fix

#42 [feature/fix] homeContents url 불러오기 오류 수정 #41
  src/components/HomeContents/HomeContents.jsx
  src/components/Popular/Popular.jsx
  src/pages/Detail/Detail.jsx
Labels: 🩹 fix

#43 [feature/formButton] 홈 페이지에서 축제폼으로 이동하는 버튼 추가 #35
  src/App.jsx
  src/components/Header.jsx
Labels: ✨ update, 🩹 fix

#45 [Feature/search form ] update: 검색 기능 추가
  src/components/SearchForm/SearchForm.jsx
  src/data/regionList.json
  src/hooks/useInput.js
Labels: ✨ update

#47 [feature/festivalRegistrationForm] 축제 등록 폼 수정 #46
  src/components/FestivalRegistration/FestivalRegistrationForm.jsx
Labels: ✨ update, 🩹 fix

#40 [feature/global-modifications] carousel, popular, 디자인 등 수정 #39
  src/components/Carousel/Carousel.jsx
  src/components/Popular/Popular.jsx
  src/styles/GlobalStyle.jsx
Labels: 🩹 fix, 💄 style

#49 [Feature/login] 로그인 페이지 홈으로 가는 버튼 추가
  src/components/Auth/GenernalLogin.jsx
  src/components/Auth/OrganizerLogin.jsx
  src/components/SearchForm/assets/imageaa.png
Labels: ✨ update

#50 Feature/kakao map
  package-lock.json
  package.json
  src/assets/geoMarker.png
  src/components/Comments/Comments.jsx
  src/components/FestivalRegistration/FestivalRegistrationForm.jsx
  src/components/Header.jsx
  src/components/KakaoMap/KakaoMap.jsx
  src/components/KakaoMap/KakaoMapMarker.jsx
  src/components/KakaoMap/KakaoOverlay.jsx
  src/components/SearchForm/SearchForm.jsx
  src/hooks/index.js
  src/hooks/useGeolocation.js
  src/hooks/useImageFile.js
  src/hooks/useInput.js
  src/hooks/useKakaoMap.js
  src/hooks/useKakaoMapMarker.js
  src/pages/Detail/Detail.jsx
  src/pages/FestivalRegistration/FestivalRegistration.jsx
  src/pages/Home/index.jsx
  src/pages/Search/Search.jsx
  src/redux/modules/authSlice.js
  src/redux/modules/festivalSlice.js
  src/shared/Layout.jsx
  src/styles/theme.js
Labels: ✨ update, 🎉 add, ♻️ refactor, 🚚 move

#51 fix : 오류 수정
  src/components/FestivalRegistration/FestivalRegistrationForm.jsx
  src/components/SearchForm/SearchForm.jsx
  src/pages/Search/Search.jsx
Labels: 🐛 bugfix

#52 feature/comments 리뷰에서 후기로 바꿈 #33
  src/components/Comments/Comments.jsx
Labels: 🩹 fix

#56 [Feature/search form] 검색 결과 UI 수정 및 검색 결과 수정
  src/components/SearchForm/SearchForm.jsx
Labels: 🩹 fix

#57 [feature/detail] 링크 복사하기, 슬라이드 버튼 수정
  src/pages/Detail/Detail.jsx
Labels: 🩹 fix

#54 [feature/carousel-edit] 슬라이드 드래그 막기, 배너 링크 추가
  src/components/Carousel/Carousel.jsx
  src/components/Popular/Popular.jsx
Labels: 🩹 fix

#58 Feature/kakao map
  src/components/FestivalRegistration/FestivalRegistrationForm.jsx
  src/components/KakaoMap/KakaoMap.jsx
  src/hooks/index.js
  src/hooks/useKakaoMap.js
  src/hooks/useKakaoMapMarker.js
  src/pages/Detail/Detail.jsx
  src/pages/FestivalRegistration/FestivalRegistration.jsx
Labels: ✨ update, 🎉 add

#60 [feature/homeContents-edit] 기간 지난 축제 숨기기
  src/components/HomeContents/HomeContents.jsx
Labels: 🩹 fix

#61 Feature/kakao map
  src/components/KakaoMap/KakaoMap.jsx
  src/components/KakaoMap/KakaoOverlay.jsx
  src/components/SearchForm/SearchForm.jsx
  src/hooks/useKakaoMapMarker.js
  src/pages/Search/Search.jsx
Labels: ✨ update, 🩹 fix
